### ISSUE TITLE
RDT Build failed

### ISSUE THREAD

**Issue by natowi** [alicevision/meshroom-manual#26]
https://readthedocs.org/projects/meshroom-manual/builds/12645037/

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/meshroom-manual/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/meshroom-manual/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 278, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/meshroom-manual/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 337, in _init_builder
    self.events.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/meshroom-manual/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/meshroom-manual/envs/latest/lib/python3.7/site-packages/sphinxcontrib/bibtex/__init__.py", line 45, in init_bibtex_cache
    raise ExtensionError("You must configure the bibtex_bibfiles setting")
sphinx.errors.ExtensionError: You must configure the bibtex_bibfiles setting

Extension error:
You must configure the bibtex_bibfiles setting

---

Looks like  "sphinx-bibtex just released a major version that's incompatible." (Dec. 2020)

https://github.com/executablebooks/jupyter-book/issues/1137#issuecomment-743993738

>In the meantime just ensure that you have sphinxcontrib-bibtex 1.0

just add  sphinxcontrib-bibtex<2.0.0 in the requirements.txt

**Comment by natowi** [comment]
Hooray, problem is fixed: https://readthedocs.org/projects/meshroom-manual/builds/13469822/

https://github.com/alicevision/meshroom-manual/commit/2e1a9de502c5447d5f106e12137e91d8057aad4e
